name: DevSecOps Pipeline Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
        - dev
permissions:
    checks: write
    security-events: write
    packages: write
    actions: write
jobs:
  # GGShield:
  #   runs-on: ubuntu-latest
  #   steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
   
    # - name: Git_guardian
    #   uses: GitGuardian/ggshield-action@v1.20.0
    #   env:
    #         GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
    #         GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
    #         GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    #         GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    #         GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
    #   continue-on-error: true
      
  Build_and_test:
    # needs: GGShield
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
            
    - name: Build Maven
      run: mvn -B package --file pom.xml

    - name: mvn test
      run: mvn surefire-report:report
      
    # - name: Build
    #   run: mvn --batch-mode -DskipTests package

    # - name: Test
    #   run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

    # - name: Report
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: Maven Tests
    #     path: target/surefire-reports/*.xml
    #     reporter: java-junit
    #     fail-on-error: true
        
        
    - uses: actions/upload-artifact@v3
      with:
        name: coffeshopartifact
        path: |
          ./target/*.jar
          
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
         name: jacoco-report
         path: |
           target/site/jacoco

         
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
          paths: |
             target/site/jacoco/jacoco.xml
          token: ${{ secrets.PAT_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 10
          debug-mode: true

    # - name: Get the Coverage info
    #   run: |
    #     echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
    #     echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
    # - name: Fail PR if overall coverage is less than 80%
    #   if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       core.setFailed('Overall coverage is less than 80%!')
  
