name: Docker_build
on:
  workflow_dispatch:
  workflow_call:
  
jobs:
 Docker_build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: coffeshopartifact
            path: ./
     
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
     
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
     
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
