name: MAIN
on:
  workflow_dispatch: 
  
permissions:
    checks: write
    security-events: write
    packages: write
    actions: write
    pull-requests: write
    
jobs:
    talisman:
      name: talisman
      uses: ./.github/workflows/talisman.yaml
      secrets: inherit
