name: MAIN
on:
  workflow_dispatch: 
  pull_request:
    branches:
      - '!dev'
    # paths-ignore:
    #   - 'dev/**'   
permissions:
    checks: write
    security-events: write
    packages: write
    actions: write
    pull-requests: write
    
jobs:
    Talisman:
      name: Talisman
      uses: ./.github/workflows/talisman.yaml
      secrets: inherit
    
    Build_Test:
      needs: Talisman
      name: Build and Test
      uses: ./.github/workflows/Build_Test.yaml
      secrets: inherit
    
    Snyk:
      needs: Build_Test
      name: Snyk_security check
      uses: ./.github/workflows/Snyk.yaml
      secrets: inherit
     
    Sbom:
      needs: Snyk
      name: Sbom
      uses: ./.github/workflows/Sbom.yaml
      secrets: inherit

    Docker_build:
      needs: Sbom
      name: Docker build
      uses: ./.github/workflows/Docker_build.yaml
      secrets: inherit

    Deployment:
      needs: Docker_build
      name: Deployment
      uses: ./.github/workflows/Deployment.yaml
      secrets: inherit
    
    
