name: Sbom
on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  Sbom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Generate SBOM
      run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom

    - name: Upload SBOM report to artifact
      uses: actions/upload-artifact@v3
      with:
          name: "sbom-${{ github.run_number }}"
          path: target/CycloneDX-Sbom.json
